### ISSUE TITLE
Docker compose up and docker run error

### ISSUE THREAD

**Issue by Barriuso** [ssrdio/SecureBank#4]
Good morning, 

I have tried the docker run and docker compose are not working at this moment. 

fail: StoreAPI.DAL.DBInitializer[0]
storeapi    |       An error occurred while seeding the database.
storeapi    |       System.TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.EnumerableMethods' threw an exception.
storeapi    |        ---> System.InvalidOperationException: Sequence contains more than one matching element
storeapi    |          at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
storeapi    |          at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
storeapi    |          at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
storeapi    |          at Microsoft.EntityFrameworkCore.EnumerableMethods..cctor()
storeapi    |          --- End of inner exception stack trace ---
storeapi    |          at Microsoft.EntityFrameworkCore.EnumerableMethods.get_AnyWithPredicate()
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.AllAnyToContainsRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
storeapi    |          at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
storeapi    |          at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
storeapi    |          at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
storeapi    |          at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
storeapi    |          at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
storeapi    |          at StoreAPI.DAL.DBInitializer.InitializeDatabase(IApplicationBuilder app) in /app/DAL/DBInitializer.cs:line 56

**Comment by GregorSpagnolo** [comment]
The issue has been resolved & a new Docker image has been pushed.
